site_name: fastrf
site_description: FastRF application, create link budgets, track compliance across project phases, fast to use, ready for use
site_url: https://github.com/fastrf-org/fastrf

theme:
    name: 'material'

repo_name: fastrf-org/fastrf
repo_url: https://github.com/fastrf-org/fastrf
edit_uri: ''

nav:
    - Introduction: 'index.md'
    - Tutorial:
      - Models: 'tutorial/models.md'
      - Types: 'tutorial/types.md'
    - Repository Mechanics:
      - Development Tooling: 'repo_mechanics/development.md'
      - Documentation Tooling: 'repo_mechanics/documentation.md'
      - Testing Overview: 'repo_mechanics/testing.md'
      - Contributing: 'repo_mechanics/contributing.md'
    - Attributions:
      - Authors: 'attributions/authors.md'

markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- markdown_include.include:
    base_path: docs
