[tool.poetry]
name = "fastrf"
version = "0.1.1"
description = "Library to create, store, query, and update Radio Frequency Models, Specs, and Reports"
authors = ["Ian Cleary <iancleary@hey.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6.1"
pydantic = "^1.5.1"
fastapi = ">=0.58,<0.62"
uvicorn = ">=0.11.5,<0.13.0"
uuid = "^1.30"
fastapi_camelcase = "^1.0.1"

[tool.poetry.dev-dependencies]
mypy = "^0.790"
black = "^20.8b1"
isort = "^5.6.4"
autoflake = "^1.4"
flake8 = "^3.8.4"
pytest = "^6.1.2"
pytest-cov = "^2.10.1"
mkdocs = "^1.1"
mkdocs-material = "^6.1.2"
markdown-include = "^0.6.0"
taskipy = "^1.4.0"
asgi-lifespan = "1.*"
httpx = "^0.16.1"
pytest-asyncio = "^0.14.0"
pre-commit = "^2.8.2"

[tool.taskipy.tasks]
test = "bash scripts/test.sh"
lint = "bash scripts/lint.sh"
format = "bash scripts/format.sh"
mkdocs = "bash scripts/docs-live.sh"
pre-commit = "pre-commit install"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
